### ISSUE TITLE
Add support for built-in constants

### ISSUE THREAD

**Issue by blakejohnson** [Qiskit/openqasm3_parser#56]
The OpenQASM spec defines the built-in constants `pi`, `tau`, and `euler` along with unicode equivalents of `π`, `τ`, and `ℇ`. We really should support all 3, but even adding just support for `pi` and `π` would cover many use cases.

**Comment by jakelishman** [comment]
fwiw, Unicode support should be relatively easy because rust-analyzer's lexer will already be needing to handle that, and Rust `String` of course handles it natively.

Taking a stab in the dark - if you're generating OQ3 from Qiskit to feed to this parser, you might want to use `qiskit.qasm3.dumps(qc, disable_constants=True)` for the time being (which imo should have been the default) so it doesn't include `pi` tokens.  Of course, we ought to support the constants as well, but just to get rolling, it's possible to make Qiskit not output them.

**Comment by jlapeyre** [comment]
This problem is similar to
* #35
which is equivalent to declaring `U` at the top of the source file. The same could be done with constants. This is probably the easiest solution. But it pollutes every ASG with a bunch of boilerplate.

It's not too hard to do something better. I could wait and make a better solution if there is time before we release. And if there's not time, follow the idea for #35 for everything.

Or I could commit #35 now and make a similar PR for the constants. Then we could replace these by a better solution at some point in the future.

**Comment by jlapeyre** [comment]
My plan now is to put the built in constants in the global symbol table. And make the `Gate` type carry number of params. So the `U` gate will also just go in the global symbol table. This will avoid polluting the AST/ASG as such. Just the symbol table will have extra stuff.

Plus this is very easy.
