### ISSUE TITLE
Design gate call and gate calls with modifiers

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/openqasm3_parser#82]
Here are two approaches to organizing representation of gate calls. Note that not all of the choices in each approach are required to be adopted together.

The first approach is taken in v 0.0.5 (and most or all lower versions) . The second approach is taken in v 0.0.6.

### Gate calls are statements, modifiers are optional fields

Previously, in v 0.0.1 (and some later versions), gate calls were organized in the ASG as variants of the `Stmt` enum. And optional gate modifiers (`ctrl`, etc.) were represented by a field in the `GateCall` struct. Like this:
https://github.com/Qiskit/openqasm3_parser/blob/d894bf85b98a1a68c54db8b534c689d8db284628/crates/oq3_semantics/src/asg.rs#L170 ...
https://github.com/Qiskit/openqasm3_parser/blob/d894bf85b98a1a68c54db8b534c689d8db284628/crates/oq3_semantics/src/asg.rs#L189

https://github.com/Qiskit/openqasm3_parser/blob/d894bf85b98a1a68c54db8b534c689d8db284628/crates/oq3_semantics/src/asg.rs#L613-L626

In this scheme, the implementation of gate modifiers was only sketched in the extent shown in the snippets above. They were not further supported in any of the crates in this repo, nor in the qiskit importer code. 

#### Problems with this approach
* Only one modifier per gate is possible. This could be solved by replacing `modifier: Option<GateModifier>` with `modifier: Vec<GateModifier>`, or some other container.
* We'd like to minimize the storage requirements for gate calls. For example for a single qubit parameterless gate call, we need a gate id and a qubit id. Carrying a reference to an array of modifiers is unnecessary. See #34

### Gate calls are expressions, and modified gate calls are separate structs.

Here we have the (unmodified) `GateCallExpr` wrapped in `ExprStmt`. And each modified gate call is a separate struct, on the same level as the unmodified gate call. A modified gate call wraps an unmodified gate call. This approach *is* implemented from end to end in this repo/workspace.

Currently, in v 0.0.6, gate calls are organized in the ASG like this:
https://github.com/Qiskit/openqasm3_parser/blob/61b5071348d4c21acd5dcf1fc0e125ee7ad02427/crates/oq3_semantics/src/asg.rs#L118 ...
https://github.com/Qiskit/openqasm3_parser/blob/61b5071348d4c21acd5dcf1fc0e125ee7ad02427/crates/oq3_semantics/src/asg.rs#L126-L130
https://github.com/Qiskit/openqasm3_parser/blob/61b5071348d4c21acd5dcf1fc0e125ee7ad02427/crates/oq3_semantics/src/asg.rs#L618-L622
https://github.com/Qiskit/openqasm3_parser/blob/61b5071348d4c21acd5dcf1fc0e125ee7ad02427/crates/oq3_semantics/src/asg.rs#L682-L684, etc.

### Advantages

* This approach makes it easier to move toward more specialized gate calls (See #34). For example
```rust
 pub struct GateCallExpr1p2q { 
     name: SymbolIdResult, 
     params: [TExpr; 2]
     qubits: [TExpr; 1], 
 } 
```
(I don't know if this would store the parameters inline, but that's what we want)

* How often will gate modifiers appear? If it is not too common, we don't want to have to account for their absence. In this approach, modifiers appear as struct's and only when they are needed. Multiple modifiers are implemented by nesting these structs.

* The fact that gate calls are represented by `Expr` (or really `TExpr`) makes it easy to compose them without incurring storage overhead for common cases. Modifying a gate call that is special cased on number of qubits is easy.

### Disadvantages

* Gate calls are not expressions. They don't evaluate to a typed value that can be plugged into any compound expression. They would be an anomaly that has to be treated specially.

The statement above is only partially true. No expression can be plugged into all compound expressions. The types of the subexpression and the slot it occupies have to be the same (or match somehow). So we could give a gate call a singleton type that it evaluates to. This would then be rejected in expression trees without requiring any special handling or machinery. In fact types could be used to validate modified gate calls to detect some programming errors. But the latter would be a potentially problematic abuse of the expression and type system. For example, if we treat `inv` as a prefix operator, it should operate on the value returned by a gate call. But semantically, this is not what happens; the `inv` actually reaches into the gate call and modifies its behavior.

### Concrete objections to the current implementation in 0.0.6

Discussion in this PR: https://github.com/jakelishman/qiskit-terra/pull/22

> I think this is a regression on the AST side - it's fine to parse the syntax as an expression, but the semantic analysis should absolutely be resolving this back to the `GateCall` statement.

> Because semantically a gate call is a separate statement - it cannot be a subcomponent of a general expression. This change pushes a bunch of semantic analysis from the semantic analyser location onto all consumers of the ASG instead.

> As in, with this change, now every place that an `Expr` is handled anywhere in all consumers needs to handle the case that a `GateCallExpr` is there, even though semantically it's not valid. Semantic analysis should be exposing a data structure that minimises the amount of data redundancy or unreachable cases that need to be handled, but this change to the parser backend has increased them.

I don't see this problem arising. If gate calls are expressions, they have to evaluate to values with a type. The improper use of a gate call will be rejected by the type analysis. So no additional semantic analysis will be pushed to consumers. In fact, at an early stage, ideally when the ASG is first constructed, they ASG should be soundly typed. Downstream consumers don't need to handle gate calls in an unexpected place. If they encounter this, it reveals a bug in the parser and semantic analyzer.

You can argue that it is better to use the type system to ensure that it is not possible to represent a program with a gate call in the wrong place. If it were possible to use the type system like this pervasively and incurring no other disadvantages, then this would be an argument against making gate calls expressions; although not necessarily an argument that trumps counter arguments. But in fact it's not at all clear to me how to used the type system to ensure that incorrect programs cannot be expressed. This touches on the design of the representations of the OQ3 programs something that needs more discussion. For example as far as I can tell, it's difficult (impossible for me so far, but a way could be found) to write generic machinery for walking the ASG. (See https://github.com/Qiskit/openqasm3_parser/blob/0.0.6/crates/oq3_semantics/src/validate.rs). Using the type system to dispatch to analysis on nodes can be slow and difficult. It may be better to use a single Rust type, and encode the type of node in an `enum` variant tag or something similar. The structure constructed by `oq3_parser` takes this approach.

### Breaking recursion in the `enum`s and `struct`s

This is a more general question and is independent of the questions above. It might need a separate issue depending on how much discussion is needed. I had been taking the compiler's suggestions for breaking recursion when a recursion is found. But it might be possible to have a sort of uniform approach that requires fewer `Box` es, and similar.

Currently, the point at which recursion is broken varies, probably due to historical accident:
https://github.com/Qiskit/openqasm3_parser/blob/61b5071348d4c21acd5dcf1fc0e125ee7ad02427/crates/oq3_semantics/src/asg.rs#L118-L126

If we break it at higher levels, for example `GateCallExpr(Box<GateCallExpr>)`, we may need fewer `Box`es.

**Comment by jlapeyre** [comment]
> I'm saying this as the author of the only consumer of this ASG right now - I've actually used the interface as defined here.

Just to be clear, I think you are talking about the pre- 0.0.6 interface, where gate calls are statements.

> It has already: the issue is in capability design of the typing. v0.0.6 allows in the typing of the ASG for a `GateCallExpr` to appear anywhere an `Expr` can, which means all consumers of the ASG have to handle the possibility, because the typing of the Rust objects does not forbid it.

But this isn't related to the question of whether a gate call should be a statement or expression(-statement) per se. It's a more generic issue. Different expressions are variants of `enum Expr`. Enforcing the correct one happens by examining the tag, not by rust-level, compile-time type errors. And usually they are used via the typed expression struct `TExpr`. Likewise all variants of  `Stmt` are of a single Rust type. Having two Rust types `Stmt` and `Expr` I suppose do something to "erase as many syntactic elements as it possibly can". But not much. I don't see how moving one of the elements from `Stmt` to `Expr` makes the problem significantly worse.

 I see the responsibility for validation similarly to what you wrote here:
https://github.com/Qiskit/qiskit/blob/052d889a7e47316515afa7576355a4ced391be4e/qiskit/qasm2/parse.py#L190-L192

>   The Rust code is responsible for all validation.  If this function causes any errors to be
    raised by Qiskit (except perhaps for some symbolic manipulations of `Parameter` objects), we
    should consider that a bug in the Rust code.

Also, as I wrote above, putting more correctness in the type system and enforcement on the rust compiler, makes a more rigid and difficult (and probably slow) representation of the QASM 3 code.

**Comment by jakelishman** [comment]
There are places, very often in representing the type system of the target language, where it's not possible to represent the restrictions within the host language in a reasonable way - that's what's happening in the OQ2 code you highlighted, and why I don't have a problem with the types of `Expr` nodes being present in the consumer interface.

This gate-call component, though, is not one of those situations.  The consumer interface presented in 0.0.5 is significantly better than the one presented in 0.0.6, because it means that an `Expr` _cannot_ include a `GateCallExpr` in a place where it cannot occur.  That's something that the parser on this side must validate (as you say), but then it can choose its output typing such that it is not possible to represent an invalid state. 


> I don't see how moving one of the elements from `Stmt` to `Expr` makes the problem significantly worse.

Because a gate call can only actually happen places that a `Stmt` is valid in the ASG, but if it's in `Expr`, then it's possible from the Rust typing to put it _anywhere_ in the tree, and that means that any enum that handles `Expr` must handle the possibility of that happening, even if it's to say `Expr::GateCall => unreachable!()`.  This encourages all branches that handle `Expr` to include a `_ => unreachable!()` or similar line, because it's not just `GateCall` that is moved here, but also there are four new identifiers, which means that they will not detect changes in the `Expr` enum in the future.

Moving `GateCall` into `Expr` and folding it into `ExprStmt` is less semantically descriptive of a program, because now the consumer code has to reparse `ExprStmt` to determine if it's a gate call, a modified gate call, or something else.

Put another way: you say that you can examine the `enum` tag to determine if something's a gate call.  This is not true in the way it is for `GateCallStmt`.  The statement based interface lets calling code do things like
```rust
for stmt in stmts {
    match stmt {
        Stmt::Declare(decl) => handle_declaration(decl),
        Stmt::GateCall(call) => handle_gate_call(call),
        Stmt::ExprStmt(expr) => handle_expr_stmt(expr),
        // ...
    }
}

fn handle_declaration(call: GateCall) {
    let mut gate = context.resolve_call(call.name());
    for modifier in call.modifiers() {
        gate = apply_modifier(gate, modifier);
    }
    append_to_circuit(gate, call.qubits())
}
```

If it's mixed into `Expr`, then not only does the `stmt` loop have to dispatch three logically different things (gate calls, assignments [since we've also talked about building the CST with those as binops], and actual stand-alone expressions-as-statements) to the same `handle_expr_stmt` function, but now _that_ has to redo parse structures like:

```rust
fn handle_expr_stmt(expr) {
    match expr {
        Expr::Modifier(mod, maybe_call) => handle_modified_gate(mod, maybe_call),
        Expr::GateCall(call) => handle_gate_call(call),
        Expr::BinaryOp(left, right, op) where op.is_assignment() => handle_assignment_stmt(left, right, op),
        _ => handle_general_expr(expr),
    }
}

fn handle_modified_gate(mod: GateModifier, maybe_call: Expr) {
    handle_modified_gate_inner(Vec::new(), mod, maybe_call)
}

fn handle_modified_gate_inner(stack: Vec<GateModifier>, mod: GateModifier, maybe_call: Expr) {
    stack.push(mod);
    let call = match maybe_call {
        Expr::Modifier(mod, maybe_call) => return handle_modified_gate_inner(stack, mod, maybe_call),
        Expr::GateCall(call) => call,
        // This is an example of needing to handle an impossible case in a consumer;
        // we must match all enum arms, so we have to tell the compiler it's impossible
        // rather than it happening automatically through typing.
        _ => unreachable!(),
    };

    // ... and only now do we get to what we could immediately jump to
    // in `handle_gate_call` in the first version.
    let mut gate = context.resolve_call(call.name());
    for modifier in stack {
        gate = apply_modifier(gate, modifier);
    }
    append_to_circuit(gate, call.qubits())
```

That's not to mention all the other places where we have to handle an `Expr` now need the same lines about `_ => unreachable!()` (or similar) once we've accounted for all the cases that could actually occur and are left with things like `GateCall` and `Modifier`.


> putting more correctness in the type system and enforcement on the rust compiler, makes a more rigid and difficult (and probably slow) representation of the QASM 3 code.

Rigid is a good thing! The representation after parsing should be rigid - it's one of the primary jobs of a parser to take the fuzzy human text-based language and turn it into something concrete.  If we were concerned with making it easy to make the representation, we wouldn't have an AST at all - we'd check the semantics, then just return the concrete syntax tree.  That's obviously no good, because it's hard to consume in a semantic context - that's why the parser exists.

Having a rigid AST doesn't make things slow or difficult.  It makes consumers fast and easy, because they don't have to reparse data structures that have already been resolved once, because it's literally impossible in the host-language typing for them to be any other way.

You're concerned about the line `modifiers: Vec<GateModifier>` in `GateCall`.  This is not actually a problem - _as written_, yes, that takes 3 pointers on the stack for each gate call statement.  It doesn't need to be like that, though - it can trivially be `modifiers: Option<Box<Vec<GateModifier>>>` which is immediately only 1 pointer with no heap allocation if there's no modifiers.  If that's still a concern, it can become `modifiers: u8` where the `u8` is actually wrapped in a newtype and is an index into a centrally managed store of `Vec<GateModifier>`, where the 0 index is guaranteed to refer to an empty `Vec` (though it's pretty likely that the `GateCall` struct will have pointer alignment anyway, so there's not actually anything gained by having a `u8` over a `usize`).  I haven't been commenting on these things, so as not to distract from delivering an initial MWE.  None of the funky types here would ever actually be exposed to users of the ASG - they'd all be hidden in well-defined interfaces like `pub fn iter_modifiers(&self) -> impl ExactSizeIterator<Item = &GateModifier>;`, which immediately abstracts all those concerns away.

Each step in a compiler pipeline is meant to make it easier for the next step.  Mixing `GateCall` into `Expr` in the final step of this package means that the next step (in this case, Qiskit land) has to re-parse each `ExprStmt` to work out if it's a gate call, an assignment, or a regular classical expression that's simply bound to nothing.  That makes it harder than having it be a separate `Stmt`, because Qiskit has to reproduce work that this parser has already done once.

**Comment by jakelishman** [comment]
As an immediate goal for me here: I'm not looking to rewrite the parser or anything like that at all.  On this particular topic, I'm just hoping to get the _ASG_ to be back what it was in 0.0.5, and have the parser on this side resolve CST `Expr` nodes into the `Stmt::GateCall`, rather than into an _ASG_ `Expr` node (and remove the `asg::Expr::GateCall` bits).

**Comment by jlapeyre** [comment]
I was in the process of replying here with something like your last comment. What *would* be acceptable. My immediate goal is getting as many of the essential things implemented from source to Qiskit circuit as possible. I don't think we are generating insurmountable (or particularly large) technical debt.

It won't take too much time ((I think) to rewrite this to use `modifiers: Vec<GateModifier>`.

**Comment by jakelishman** [comment]
Reverting the public ASG to the state of 0.0.5 is ideal and then handling the resolution of the CST in the parser here so that the ASG comes out like that.  If you're able to do that, it would be great, thank you.

Any time it takes you to do that here is time either you or I would have had to spent on the Qiskit side for the MWE anyway, except that if it's done on the Qiskit side, then any _other_ consumer of the ASG will have to spend the time as well. It was simple enough in jakelishman/qiskit-terra#22 when gate modifiers weren't handled and `Expr` nodes were largely not being handled in any other context other than "I'll handle an `IntegerLiteral` and just explode if it's not", but those things are very temporary situations.

**Comment by jlapeyre** [comment]
> Reverting the public ASG to the state of 0.0.5 is ideal

except for `modifiers: Option<GateModifier>`  becomes  `modifiers: Vec<GateModifier>`, right?

**Comment by jakelishman** [comment]
Right yeah - I keep forgetting that it wasn't actually like that already.

**Comment by jlapeyre** [comment]
I don't think we will be motivated to change this a related performance problem or similar arises.
