### ISSUE TITLE
Physical qubit identifiers do not work in gate calls

### ISSUE THREAD

**Issue by blakejohnson** [Qiskit/openqasm3_parser#84]
I can use physical qubit identifiers in `measure` commands, i.e. this works:
```
bit c;
c = measure $0;
```

but I cannot use them in gate calls, i.e. this fails:
```
gate x q {}
x $0;
```
The latter one should also work.

**Comment by jlapeyre** [comment]
Thanks for catching this.

This is fixed by changing
https://github.com/Qiskit/openqasm3_parser/blob/61b5071348d4c21acd5dcf1fc0e125ee7ad02427/crates/oq3_parser/src/grammar/expressions/atom.rs#L90

to 
```
IDENT if (la == IDENT || la == HARDWAREIDENT) => gate_call_expr(p)
```

I will push a PR for redesign of gate modifiers in a few minutes. I'll push a PR for this issue afterward.

Just to be clear, the parser looks at the first qubit argument to dispatch to parsing a gate call. Hardware qubits in positions other than the first already work. For example, this is not currently broken:
```
gate cx q0, q1 {}
qubit q0;
cx q0, $0;
```
